{
 "title": "Zeebe",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Partition Leader",
     "type": "table",
     "description": "Shows for each partition which broker is the leader",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"} >= 3",
       "legendFormat": "{{pod}} {{partitionGroupName}} {{partition}}"
      }
     ]
    },
    {
     "title": "Health",
     "type": "stat",
     "description": "Shows accumulated health per partition",
     "gridPos": { "h": 6, "w": 9, "x": 8, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(zeebe_health{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "description": "Shows when and how often a pod was restarted.  The graph is zero when the pod is ready. With this it is also possible to determine how long it take for the pod to come ready again.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "1 - kube_pod_container_status_ready{pod=~\"$pod\", pod!~\".*curator.*|worker.*|starter.*\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"worker\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Worker restart"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_ready{container=\"starter\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m])) or vector(1)",
       "legendFormat": "Starter Restart"
      }
     ]
    },
    {
     "title": "Processing per Partition",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"skipped|processed\"}[1m])) by (pod, partition, processor)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-processed"
      },
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written\"}[1m])) by (pod, partition, processor)",
       "legendFormat": "{{pod}}-{{partition}}-{{processor}}-written"
      }
     ]
    },
    {
     "title": "Exporting per Partition",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (pod, partition, exporter)",
       "legendFormat": "{{pod}}-{{partition}}-exported"
      }
     ]
    },
    {
     "title": "Requests handled by Gateway per sec",
     "type": "graph",
     "description": "Requests which hit the gateway and a response have been sent to the client per second.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}} Request"
      }
     ]
    },
    {
     "title": "Overall FNI  per s [1m]",
     "type": "stat",
     "description": "Flow node instances completed or terminated per second over all partitions.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type!=\"PROCESS\", action!=\"activated\"}[1m]))",
       "legendFormat": "Partition {{partition}} FNI per s"
      }
     ]
    },
    {
     "title": "Current Events",
     "type": "graph",
     "description": "Shows the current processed records",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (type, action)",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Completed Tasks in avg overtime per sec",
     "type": "stat",
     "description": "Takes the avg of all completed tasks per second over the given time range.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "Completed Processes in avg overtime per sec",
     "type": "stat",
     "description": "Takes the avg of all completed processes per second over the given time range.",
     "gridPos": { "h": 2, "w": 9, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[1m]))",
       "legendFormat": "{{type}} {{action}}"
      }
     ]
    },
    {
     "title": "PVC Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Backpressure Dropping Requests [1m]",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) / sum(rate(zeebe_received_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) ) * 100",
       "legendFormat": "Partition {{partition}}"
      },
      {}
     ]
    },
    {
     "title": "Process memory usage",
     "type": "graph",
     "description": "Memory limits and requests are taken from the k8 pod metrics.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 90 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"}",
       "legendFormat": "{{pod}} RSS"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", container=~\"zeebe.*\"})",
       "legendFormat": "request"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processing Queue size",
     "type": "graph",
     "description": "Shows the processing queue size over time. Processing queue defines, what is already appended but not yet processed by the stream processor.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_appended_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Number of records exported but not acknowledged",
     "type": "gauge",
     "description": "Shows how many positions are not updated by exporters per partition. Means what is the difference between last committed exporter position and committed log position.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (exporter, pod, partition) (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (exporter, pod, partition) (zeebe_exporter_last_updated_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "{{exporter}} {{partition}} {{pod}}"
      }
     ]
    },
    {
     "title": "Last appended position",
     "type": "table-old",
     "description": "Shows the position, which was appended last by the leader per partition.",
     "gridPos": { "h": 4, "w": 7, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_appended_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last committed position",
     "type": "table-old",
     "description": "Shows the last committed log position.",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 81 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Number of records not exported",
     "type": "gauge",
     "description": "Shows how many records are not exported yet.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) by (partition) - max (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"}) by (partition)",
       "legendFormat": "Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Last updated exported position",
     "type": "table-old",
     "description": "Shows the last exported position which was committed by the given exporter per partition.",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 85 },
     "targets": [
      {
       "expr": "max by (exporter, partition) (zeebe_exporter_last_updated_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last processed position",
     "type": "table-old",
     "description": "Shows the last processed position by the stream processor per partition.",
     "gridPos": { "h": 12, "w": 5, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Last replayed source position",
     "type": "table-old",
     "description": "Shows the last replayed source position by the stream processor per partition and pod",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 85 },
     "targets": [
      {
       "expr": "max by (partition, pod) (zeebe_replay_last_source_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})"
      }
     ]
    },
    {
     "title": "Number of records not processed",
     "type": "gauge",
     "description": "Shows how many records the stream processor has not processed yet.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_log_appender_last_committed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}) - max by (partition) (zeebe_stream_processor_last_processed_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"})",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Last exported position",
     "type": "table-old",
     "description": "Shows the last exported position per partition.",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 91 },
     "targets": [
      {
       "expr": "max by (partition) (zeebe_exporter_last_exported_position{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", exporter=\"elasticsearch\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process Instance Events per second (range = 1m)",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)"
      }
     ]
    },
    {
     "title": "Job events per second (range = 1m)",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Stream Processor"
      }
     ]
    },
    {
     "title": "Process Instance Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}) by (action)",
       "legendFormat": "Process Instance ({{action}})"
      },
      {
       "expr": "sum(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Process Instance Events per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", type=\"PROCESS\"}[1m])) by (action)",
       "legendFormat": "Process Instance ({{action}})"
      },
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action)",
       "legendFormat": "Job ({{action}})"
      }
     ]
    },
    {
     "title": "Processed Commands",
     "type": "graph",
     "description": "Processed commands by the leading Stream Processor",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (action, partition)",
       "legendFormat": "Partition {{partition}} ({{action}})"
      }
     ]
    },
    {
     "title": "Exported Records",
     "type": "graph",
     "description": "Exported Records by the leading Stream Processor",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition, pod)",
       "legendFormat": "{{pod}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Replayed Events",
     "type": "graph",
     "description": "Replayed events by the following Stream Processor",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_replay_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition, pod)",
       "legendFormat": "{{pod}} Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Process instance creation per second [1m]",
     "type": "graph",
     "description": "Shows the process instance creation rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"activated\"}[1m])) by (namespace)",
       "legendFormat": "Process instance creation {{namespace}}"
      }
     ]
    },
    {
     "title": "Process instance completion per second [1m]",
     "type": "graph",
     "description": "Shows the process instance completion rate over all partitions in the namespace. It will only count root process instances, so call activity process instance creations are excluded.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_executed_instances_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[1m])) by (namespace)",
       "legendFormat": "Process instance completion {{namespace}}"
      }
     ]
    },
    {
     "title": "Job creation per second [1m]",
     "type": "graph",
     "description": "Shows the Job creation rate over all partitions in the namespace",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"created\"}[1m])) by (namespace)",
       "legendFormat": "Job creation {{namespace}}"
      }
     ]
    },
    {
     "title": "Job completion per second [1m]",
     "type": "graph",
     "description": "Shows the Job completion rate over all partitions in the namespace.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_job_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", action=\"completed\"}[1m])) by (namespace)",
       "legendFormat": "Job completion {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Snapshot Count",
     "type": "graph",
     "description": "Total number of committed snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_snapshot_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[1m])",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Operation Duration",
     "type": "heatmap",
     "description": "Approximate duration of taking a single snapshot from the processor point-of-view (without replication or committing).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Snapshot Size",
     "type": "graph",
     "description": "Size in bytes of snapshots on disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_size_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Files Sizes (1m)",
     "type": "heatmap",
     "description": "Distribution of snapshot file sizes - each snapshot may be comprised of many files, and this shows approximately how \"big\" files there are and how many \"small\" files.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_snapshot_file_size_megabytes_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of files in a snapshot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_snapshot_chunks_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process memory usage",
     "type": "graph",
     "description": "Memory limits and requests are taken from the k8 pod metrics.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*zeebe.*\", container=~\"zeebe.*\"}",
       "legendFormat": "{{pod}} RSS"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*zeebe.*\", container=~\"zeebe.*\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\".*zeebe.*\", container=~\"zeebe.*\"})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "GC Count per second [1m]",
     "type": "graph",
     "description": "Shows the number of garbage collections (GC) per second, aggregated per pod and GC type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (gc, pod)",
       "legendFormat": "{{pod}} {{gc}}"
      }
     ]
    },
    {
     "title": "GC proportion per second [1m]",
     "type": "graph",
     "description": "Shows the garbage collection (GC) time proportion per second. Means shows the rate which is spent in GC in a second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "{{pod}} {{gc}}"
      }
     ]
    },
    {
     "title": "JVM Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
       "legendFormat": "{{pod}} JVM heap"
      }
     ]
    },
    {
     "title": "Buffer Pool Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (jvm_buffer_pool_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}) by (namespace,pod,pool)",
       "legendFormat": "Used {{pod}}:{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JVM Thread count",
     "type": "graph",
     "description": "Current thread count of a JVM, aggregated by namespace and pod",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "JVM Threads on {{pod}} (ns: {{namespace}})"
      },
      {
       "expr": "jvm_threads_daemon{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "JVM daemon threads on {{pod}} (ns: {{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PVC Disk Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*zeebe.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} use fds"
      },
      {
       "expr": "process_files_max_files{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} limit"
      }
     ]
    },
    {
     "title": "PVC Disk Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Read bytes/s [1m]",
     "type": "graph",
     "description": "Shows the bytes read per second for the zeebe pods in the select namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Written bytes/s [1m]",
     "type": "graph",
     "description": "Shows the written bytes per second by the Zeebe pods in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s transmitted [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods transmit per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network bytes/s received [1m]",
     "type": "graph",
     "description": "Shows how many bytes the Zeebe Pods have received per second in the selected namespace.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messaging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": " Request response latency",
     "type": "heatmap",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Request size distribution",
     "type": "heatmap",
     "description": "Shows the general request size distribution",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Request response latency quantiles",
     "type": "timeseries",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p50 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p90 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_messaging_request_response_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p99 {{topic}}"
      }
     ]
    },
    {
     "title": "Request size quantiles",
     "type": "timeseries",
     "description": "Shows the general latency for request-responses in zeebe.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p50 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p90 {{topic}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_messaging_request_size_kb_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (topic, le))",
       "legendFormat": "p99 {{topic}}"
      }
     ]
    },
    {
     "title": "Inflight request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(zeebe_messaging_inflight_requests) by (pod, address)",
       "legendFormat": "{{pod}} => {{address}} "
      }
     ]
    },
    {
     "title": "Request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_request_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod, address, topic)",
       "legendFormat": "{{topic}}: {{pod}} => {{address}}"
      }
     ]
    },
    {
     "title": "Response failure count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_response_count_total{namespace=~\"$namespace\", pod=~\"$pod\", outcome!=\"SUCCESS\"}[1m])) by (address, topic, outcome)",
       "legendFormat": "{{topic}} {{address}} {{outcome}}"
      }
     ]
    },
    {
     "title": "Request count per type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_messaging_request_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process Instance Execution Time",
     "type": "heatmap",
     "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Process Instance Execution Time (avg)",
     "type": "graph",
     "description": "Shows the execution time of a process instance. This means the time (latency) between creating the instance and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le))",
       "legendFormat": "quantile-50th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(zeebe_process_instance_execution_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le))",
       "legendFormat": "quantile-99th"
      }
     ]
    },
    {
     "title": "Job Activation Time",
     "type": "heatmap",
     "description": "Shows the time (latency) between creating the job and activating it.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_activation_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Job Life Time",
     "type": "heatmap",
     "description": "Shows the complete lifetime of an job. This means the time (latency) between creating the job and completing it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_job_life_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Overall Processing Latency",
     "type": "heatmap",
     "description": "Shows the time (latency) between writing the command to the dispatcher and processing the record.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Record Processing Duration",
     "type": "heatmap",
     "description": "Time taken to process a record",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_stream_processor_processing_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch Event Replay Duration",
     "type": "heatmap",
     "description": "Time taken to replay a batch of events",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_replay_event_batch_replay_duration_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Commit Latency Quantiles",
     "type": "graph",
     "description": "Shows the quantiles of: time taken to commit a record to the log (includes write latency)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "p90 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "p99 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.50, rate(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "MEDIAN partition {{partition}} "
      },
      {
       "expr": "sum(rate(zeebe_log_appender_commit_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition) / sum(rate(zeebe_log_appender_commit_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition) ",
       "legendFormat": "AVG partition {{partition}}"
      }
     ]
    },
    {
     "title": "Record Write Quantiles",
     "type": "graph",
     "description": "Shows the quantiles of: time taken to append a record to the log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "p90 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "p99 partition {{partition}}"
      },
      {
       "expr": "histogram_quantile(0.50, rate(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "MEDIAN partition {{partition}} "
      },
      {
       "expr": "sum(rate(zeebe_log_appender_append_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition) / sum(rate(zeebe_log_appender_append_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition) ",
       "legendFormat": "AVG partition {{partition}}"
      }
     ]
    },
    {
     "title": "Commit latency",
     "type": "heatmap",
     "description": "Time taken to commit a record to the log (includes write latency)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_log_appender_commit_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Record write latency",
     "type": "heatmap",
     "description": "Time taken to append a record to the log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_log_appender_append_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total gRPC requests",
     "type": "graph",
     "description": "Shows counts of all gRPC messages, which have been sent to the Zeebe Cluster.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      }
     ]
    },
    {
     "title": "gRPC requests per second (range = 1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (grpc_method, code)",
       "legendFormat": "{{grpc_method}} ({{code}})"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "Total requests completed"
      }
     ]
    },
    {
     "title": "Create Process Instance Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CreateProcessInstance\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Activate Jobs Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"ActivateJobs\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Complete Job Latency (gRPC)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", grpc_method=\"CompleteJob\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Gateway Request Latency",
     "type": "heatmap",
     "description": "Shows the latency (RTT) of a sent from the gateway to the broker.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_gateway_request_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Failure Error Code",
     "type": "graph",
     "description": "Shows rate of each error type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_gateway_failed_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", error=~\".*\"}[15s]) / rate(zeebe_gateway_total_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[15s])",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "Failure Rate by Request Type",
     "type": "graph",
     "description": "Shows failure rate of requests sent from gateway to the broker.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (requestType) (rate(zeebe_gateway_failed_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) / \nsum by (requestType) (rate(zeebe_gateway_total_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[30s]))",
       "legendFormat": "{{requestType}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Raft requests per second [1m]",
     "type": "graph",
     "description": "Shows the rate of different raft requests send from the leader to different followers",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "sum(rate(atomix_raft_messages_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m])) by (pod, partition, to, type)",
       "legendFormat": "{{pod}} {{partition}} send {{type}} to {{to}}"
      }
     ]
    },
    {
     "title": "Compacting time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum(increase(atomix_compaction_time_ms_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Creation Time",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_creation_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total install requests send",
     "type": "graph",
     "description": "Shows the total count of send install requests from the leader to the followers",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short", "label": "Install Requests" }
     ],
     "targets": [
      {
       "expr": "atomix_raft_messages_send_total{cluster=~\"$cluster\", namespace=~\"$namespace\", type=\"InstallRequest\"}",
       "legendFormat": "{{pod}} {{partition}} send {{type}} to {{to}}"
      }
     ]
    },
    {
     "title": "Snapshot Replication Duration",
     "type": "graph",
     "description": "Approximate Install RPC as measured by the follower.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_duration_milliseconds{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Snapshot Replications",
     "type": "graph",
     "description": "Ongoing snapshot replications per partition, from the follower point-of-view.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_snapshot_replication_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} {{partitionGroupName}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum(increase(atomix_segment_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Segment Flush Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(atomix_segment_flush_time_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (pod) / sum(rate(atomix_segment_flush_time_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m]))  by (pod)",
       "legendFormat": "Avg {{ pod }}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(atomix_segment_flush_time_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Append Entry Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "sum(increase(atomix_append_entries_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "AppendEntry latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(atomix_append_entries_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) / sum(rate(atomix_append_entries_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m]))",
       "legendFormat": "Avg"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(atomix_append_entries_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Time Between Heartbeats",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_time_in_s_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Heartbeat Miss Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(atomix_heartbeat_miss_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}[1m])) by (pod, partition)",
       "legendFormat": "{{pod}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Role changes over time",
     "type": "graph",
     "description": "Shows when a role change has happened. \n1 = Follower\n2 = Candidate\n3 = Leader\n2 - ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "short", "label": "Role (3 = Leader)" }
     ],
     "targets": [
      {
       "expr": "atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Number of log segements",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_segment_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}}"
      }
     ]
    },
    {
     "title": "Commit Index",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 141 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_commit_index{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}} "
      }
     ]
    },
    {
     "title": "Index of last appended entry",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 146 },
     "repeat": "partition",
     "targets": [
      {
       "expr": "atomix_partition_raft_append_index{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}-p{{partition}}"
      }
     ]
    },
    {
     "title": "Number of records appended on the leader but not committed",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 151 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(atomix_partition_raft_append_index{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace) - max(atomix_partition_raft_commit_index{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace)",
       "legendFormat": "Partition {{partition}} ({{namespace}})"
      }
     ]
    },
    {
     "title": "Number of records by which the slowest follower is lagging behind",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 151 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(atomix_partition_raft_commit_index{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace) - min(atomix_partition_raft_commit_index{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\"}) by (partition, namespace)",
       "legendFormat": "Partition {{partition}} ({{namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RocksDB Memory usage",
     "type": "graph",
     "description": "Sum of memtable, table reader and cache memory capacity.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum(zeebe_rocksdb_memory_estimate_table_readers_mem{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",  partition=~\"$partition\"}) by (pod, partition)) + (sum(zeebe_rocksdb_memory_block_cache_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)) + (sum(rate(zeebe_rocksdb_live_estimate_num_keys{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",  partition=~\"$partition\"}[1m])) by (pod, partition) * 10)",
       "legendFormat": "{{pod}} memory {{partition}}"
      }
     ]
    },
    {
     "title": "Estimated Number of Keys",
     "type": "graph",
     "description": "Estimated total number of keys in the database per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_estimate_num_keys{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} {{partition}} keys {{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Estimated Live Data",
     "type": "graph",
     "description": "Estimated amount of live data in bytes per column family",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_live_estimate_live_data_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} live data {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. size of all mem tables",
     "type": "graph",
     "description": "Returns approximate size of active, unflushed immutable, and pinned immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L807",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} All Memtable's {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current all mem table size",
     "type": "graph",
     "description": "Approximate size of active and unflushed immutable memtables (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L803",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_all_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Approx. current active mem table size",
     "type": "graph",
     "description": "Approximate size of active memtable (bytes) per partition.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L799",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_cur_size_active_mem_table{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Memtable {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache capacity",
     "type": "graph",
     "description": "The block cache capacity per column family",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache {{partition}}"
      }
     ]
    },
    {
     "title": "Block cache usage",
     "type": "graph",
     "description": "The current usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_usage{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Block cache usage {{partition}}"
      }
     ]
    },
    {
     "title": "Pinned block cache usage",
     "type": "graph",
     "description": "The current pinned usage of the block cache per column family\n\nhttps://github.com/facebook/rocksdb/blob/618bf638aabce21262228509e9f99c1c13de2b57/include/rocksdb/cache.h#L261",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_block_cache_pinned_usage{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} pinned cache {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of live SST files",
     "type": "graph",
     "description": "Total size (bytes) of all SST  files belong to the latest LSM tree.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L882",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_live_sst_files_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  live sst {{partition}}"
      }
     ]
    },
    {
     "title": "Total size of all SST files",
     "type": "graph",
     "description": "Total size (bytes) of all SST files.\n\nWARNING: may slow down online queries if there are too many files.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L878",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_sst_total_sst_files_size{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  total sst {{partition}}"
      }
     ]
    },
    {
     "title": "Write stopped",
     "type": "table-old",
     "description": "Return 1 if write has been stopped.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L908",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_is_write_stopped{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  stopped write {{partition}}"
      }
     ]
    },
    {
     "title": "Actual write delay rate",
     "type": "graph",
     "description": "The current actual delayed write rate. 0 means no delay.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L905",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_writes_actual_delayed_write_rate{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}  delayed write {{partition}}"
      }
     ]
    },
    {
     "title": "Number of entries in immutable mem Tables",
     "type": "graph",
     "description": " Return sum of number of entries in all the immutable mem tables.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_live_num_entries_imm_mem_tables{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{columnFamilyName}}"
      }
     ]
    },
    {
     "title": "Running flush",
     "type": "graph",
     "description": "Returns the number of currently running flushes.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L783",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_flushes{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  flush {{partition}}"
      }
     ]
    },
    {
     "title": "Running compactions",
     "type": "graph",
     "description": "The number of currently running compactions.\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L791",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_writes_num_running_compactions{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}}  compaction {{partition}}"
      }
     ]
    },
    {
     "title": "Table Reader Memory ",
     "type": "graph",
     "description": "Returns estimated memory used for reading SST tables, excluding memory used in block cache (e.g., filter and index blocks).\n\nhttps://github.com/facebook/rocksdb/blob/e66199d848cd484b816d07359f1dc0f0b99e5351/include/rocksdb/db.h#L832",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_rocksdb_memory_estimate_table_readers_mem{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (pod, partition)",
       "legendFormat": "{{pod}} Table Reader {{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Elasticsearch Exporter (Flush Duration)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_flush_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Flush Failure Rate)",
     "type": "graph",
     "description": "The rate of failure of flush operations, averaged over 15s intervals",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_elasticsearch_exporter_failed_flush_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[15s]) / rate(zeebe_elasticsearch_exporter_flush_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[15s])",
       "legendFormat": "{{pod}} Exporter {{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Size)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_elasticsearch_exporter_bulk_size_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[30s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Exporter (Bulk Memory Size)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zeebe_elasticsearch_exporter_bulk_memory_size{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",partition=~\"$partition\"}",
       "legendFormat": "{{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Elasticsearch disk usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\"elastic.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Start up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Atomix Partition Server Startup time",
     "type": "bargauge",
     "description": "Time taken to start and bootstrap partition servers.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "atomix_partition_server_startup_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": " Start {{pod}} p{{partition}}"
      },
      {
       "expr": "atomix_partition_server_bootstrap_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "Bootstrap  {{pod}} p{{partition}}"
      }
     ]
    },
    {
     "title": "Streamprocessor Recovery Time",
     "type": "bargauge",
     "description": "Time taken to recover and reprocess events",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "zeebe_stream_processor_startup_recovery_time{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}",
       "legendFormat": "{{pod}}:Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Leader transition duration",
     "type": "bargauge",
     "description": "The time needed to install all leader services on a newly elected leader until it is ready to process new requests.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zeebe_leader_transition_latency{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: Partition {{ partition }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current In-Progress Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_in_progress{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\", operation=\"take\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Completed Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"take\", result=\"completed\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Status Query Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(zeebe_backup_operations_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"status\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Take Backup Latency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (partition) (rate(zeebe_backup_operations_latency_sum{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h]) / rate(zeebe_backup_operations_latency_count{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\", partition=~\"$partition\", operation=\"take\"}[1h]))",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Total Backup Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (operation, result)",
       "legendFormat": "{{operation}}: {{result}}"
      }
     ]
    },
    {
     "title": "Failed Backups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_backup_operations_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", operation=\"take\", result=\"failed\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Total Checkpoint Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Checkpoint Positions",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_position{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    },
    {
     "title": "Current Checkpoint ID",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(zeebe_checkpoint_id{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}) by (partition)",
       "legendFormat": "Partition {{partition}}"
      }
     ]
    }
   ]
  }
 ]
}