global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: zeebe
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 'host.docker.internal:9600'
